import Head from "next/head";
import { useState, useEffect } from "react";
const functionsList = [
  "cube",
  "square",
  "double",
  "pow",
  "log",
  "sin",
  "cos",
  "tan",
  "cot",
  "cosec",
  "sec",
  "sigma",
  "delta",
  "area",
  "perimeter",
];
export default function Home() {
  const [code, setCode] = useState("");
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [functions, setFunctions] = useState(functionsList);

  useEffect(() => {
    if (code.includes(".")) {
      const funcName = code.substring(code.lastIndexOf(".") + 1);
      setFunctions(functionsList.filter((fn) => fn.includes(funcName)));
    }
  }, [code]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center min-h-screen w-full bg-indigo-100 p-20">
        <div className="font-semibold text-3xl mb-4">Enter your code!</div>
        <div className="w-96 relative">
          <input
            value={code}
            onChange={(e) => {
              setCode(e.target.value);
              if (
                !e.target.value.endsWith(".") &&
                !e.target.value.includes(".")
              ) {
                setShowSuggestions(false);
              }
            }}
            onKeyDown={(e) => {
              if (e.key == ".") {
                setShowSuggestions(true);
              }
            }}
            placeholder="Enter your code here..."
            className="rounded-xl resize-none px-3 py-2 outline-none drop-shadow-lg w-full"
          />
          {showSuggestions && (
            <div
              className={`w-96 max-h-[300px] overflow-y-scroll flex flex-col bg-white p-2 rounded-lg gap-1 fixed border`}>
              {functions.map((fn, idx) => (
                <div
                  key={idx}
                  className="cursor-pointer w-full"
                  onClick={() => {
                    setCode(
                      (prev) =>
                        prev.substring(0, prev.lastIndexOf(".") + 1) + fn + "()"
                    );
                    setShowSuggestions(false);
                  }}>
                  {fn}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
